dais/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, re_path, include

from dais import views

urlpatterns = [
    re_path(
        r'^top/$',
        views.top,
        name='top'
    ),
    path(
        r'top/<int:page>/',
        views.top,
        name='top'
    ),
    re_path(
        r'^new/$',
        views.new,
        name='new'
    ),
    re_path(
        r'^submit/$',
        views.submit,
        name='submit'
    ),
    re_path(
        r'^user/$',
        views.user,
        name='user'
    ),
    re_path(
        r'^login/$',
        auth_views.LoginView.as_view(template_name="login.html"),
        name="login"
    ),
    re_path(
        r'^signup/$',
        views.signup,
        name="signup"
    ),
    re_path(
        r'^logout/$',
        auth_views.LogoutView.as_view(),
        name="logout"
    ),
    re_path(
        r'^ajax/upvote/$',
        views.upvote,
        name="upvote"
    ),
    re_path(
        r'^$',
        views.redirect_homepage,
        name="redirect"
    ),

]

nerdnews/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'', include('dais.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dais/forms.py
from django import forms


class SignupForm(forms.Form):
    username = forms.CharField(
        required = True,
        label = 'Username',
        max_length = 32
    )
    email = forms.CharField(
        required = True,
        label = 'Email',
        max_length = 32,
    )
    password = forms.CharField(
        required = True,
        label = 'Password',
        max_length = 32,
        widget = forms.PasswordInput()
    )


class SubmitForm(forms.Form):
    title = forms.CharField(
        required = True,
        label = 'Title',
        max_length = 255
    )
    url = forms.CharField(
        required = True,
        label = 'URL',
        max_length = 200,
    )

nerdnews/templates/header.html
{% load staticfiles %}
<head>
  <title>{{ title }} | NerdNews</title>
  <meta charset="utf-8">
  <link rel="stylesheet" href="{% static 'index.css' %}">
</head>

nerdnews/templates/list.html
<div class="news-view view">
  <div class="news-list">
    <ul>
    {% for item in news_items %}
      <li class="news-item">
        <span id="item-{{item.id}}" class="score">{{ item.score }}</span>
        <span class="title">
          <a href="{{ item.url }}" target="_blank" rel="noopener"> {{ item.title }} </a>
          <span class="host"> {{ item.host }}</span>
        </span>
        <br>
        <span class="meta">
          <span class="by">by <a href="/u/{{ item.user }}" class="">{{ item.user }}</a></span><span class="time"> {{ item.humanize_time }} </span><span class="comments-link">| <a href="/i/{{ item.id }}" class="">{{ item.num_comments }} comments</a></span></span>{% if request.user.is_authenticated %}| <a href="#" data-id="{{ item.id }}" class="upvote meta"> Upvote</a>{% endif %}
      </li>
    {% endfor %}
  </div>
  <div class="news-list-nav"><a {% if has_prev %} href="{% url 'top' prev_page %}" {% else %} class="disabled" {% endif %}>&lt; prev</a><span>{{ page }}/{{ num_pages }}</span><a {% if has_next %} href="{% url 'top' next_page %}" {% else %} class="disabled" {% endif %}>more &gt;</a></div>
</div>

nerdnews/templates/login.html
<html>
  {% include "header.html" %}
  <body>
    <div id="app">
      {% include "navbar.html" %}
      <div class="news-view view">
        <form class="news-item m-t-3" method="POST">
          {% csrf_token %}
          <p>
            <label>Username</label>
            <input type="text" name="username">
          </p>
          <p>
            <label>Password</label>
            <input type="password" name="password">
          </p>
          <button type="submit">Login</button>
        </form>
        <a href="{% url 'signup' %}">No account? Sign up</a>
      </div>
    </div>
  </body>
</html>

nerdnews/templates/navbar.html
{% load staticfiles %}
      <header class="header">
        <nav class="inner">
          <a href="/" class="">
            <img src="{% static 'y18.gif' %}" alt="logo" class="logo" />
          </a>
          <a href="{% url 'top' %}" {% if top_active %} class="link-active" {% endif %}>Top</a>
          <a href="{% url 'new' %}" {% if new_active %} class="link-active" {% endif %}>New</a>
          <a href="{% url 'submit' %}" {% if submit_active %} class="link-active" {% endif %}>Submit</a>
          <div class="float-right">
            {% if request.user.is_authenticated %}
            <a href="{% url 'user' %}" class="link-active link-margin-less"> {{request.user.username}}({{karma}})</a><div class="divider"></div><a href="{% url 'logout' %}" class="link-active">Logout</a>
            {% else %}
            <a href="{% url 'login' %}" {% if active %} class="link-active" {% endif %}>Login</a>
            {% endif %}
          </div>
        </nav>
      </header>

nerdnews/templates/new.html
<html>
  {% include "header.html" %}
  <body>
    <div id="app">
      {% include "navbar.html" %}
      {% include "list.html" %}
    </div>
  </body>
  <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
  <script>
    $(".upvote").on("click", function () {
      var $this = $(this);
      var itemId = $this.attr('data-id');

      $.ajax({
        url: '{% url "upvote" %}',
        data: {
          'item_id': itemId
        },
        dataType: 'json',
        success: function (data) {
          console.log(data);
          console.log(data.vote);
          if (data.vote) {
            $('#item-'+itemId).text(data.vote);
          }
        }
      });

    });
  </script>
</html>

nerdnews/templates/signup.html
<html>
  {% include "header.html" %}
  <body>
    <div id="app">
      {% include "navbar.html" %}
      <div class="news-view view">
        <form class="news-item m-t-3" method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">Submit</button>
        </form>
      </div>
    </div>
  </body>
</html>

nerdnews/templates/submit.html
<html>
  {% include "header.html" %}
  <body>
    <div id="app">
      {% include "navbar.html" %}
      <div class="news-view view">
        <form class="news-item m-t-3" method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">Submit</button>
        </form>
      </div>
    </div>
  </body>
  <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
  <script>
    $("#id_url" ).mouseout(function() {
      $this = $(this);
      url = $this.val();
      $.ajax({
        url: url,
        type: 'GET',
        success: function(data) {
          match = data.match(/<title[^>]*>([^<]+)<\/title>/)[1];
          if (!$('#id_title').val()) {
            $('#id_title').val(unescape(match));
          }
        }
      })
    })
  </script>
</html>

nerdnews/templates/top.html
<html>
  {% include "header.html" %}
  <body>
    <div id="app">
      {% include "navbar.html" %}
      {% include "list.html" %}
    </div>
  </body>
  <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
  <script>
    $(".upvote").on("click", function () {
      var $this = $(this);
      var itemId = $this.attr('data-id');

      $.ajax({
        url: '{% url "upvote" %}',
        data: {
          'item_id': itemId
        },
        dataType: 'json',
        success: function (data) {
          if (data.vote) {
            $('#item-'+itemId).text(data.vote);
          }
        }
      });

    });
  </script>
</html>